source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'iGenFamilyTree' do
    pod 'Alamofire', '~> 4.4'
    pod 'AGi18n', '~> 0.0'
    pod 'DeviceKit', '~> 1.0'
    pod 'SVProgressHUD', '~> 2.1'
end
